# title: Augustina Ashie
# # description: 
# # ![Photo](/assets/IMG_7794_edit.jpg)
# show_downloads: false
# theme: jekyll-theme-minimal
# # remote_theme: pages-themes/minimal@v0.2.0
# exclude:
#   - assets


# site settings
title: Augustina Ashie
subtitle: by HTML5 UP
email: augustinaashie@hotmail.com
# description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
country: Canada
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/augustina2023
  GitLab:
  LinkedIn: www.linkedin.com/in/augustina-ashie-729254143

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

